// <auto-generated />
using GlobalgeoBits_Task.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlobalgeoBits_Task.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240625132149_Data-Seeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalgeoBits_Task.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Rayban",
                            Color = "red",
                            Model = "xyz",
                            Name = "Rayban xyz red",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Police",
                            Color = "white",
                            Model = "abc",
                            Name = "Police abc white",
                            Price = 0m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Fred",
                            Color = "Black",
                            Model = "vvv",
                            Name = "Fred vvv red",
                            Price = 0m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Rayban",
                            Color = "purble",
                            Model = "abc",
                            Name = "Rayban abc purble",
                            Price = 0m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Police",
                            Color = "red",
                            Model = "xyz",
                            Name = "Police xyz green",
                            Price = 0m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Rayban",
                            Color = "red",
                            Model = "xyz",
                            Name = "Fred ccc red",
                            Price = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
